# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false
pandoc_version: 1.19.2.1
env:
  global:
  - ENCRYPTION_LABEL: "4cbefdc5579e"
notifications:
  email:
    on_success: change
    on_failure: change
script: .travis/deploy.sh
